[gdb/testsuite] Fix ERROR: can't read _line_unit_advertised_version: no such variable
With test-case gdb.base/until-trailing-insns.exp I run into:
...
ERROR: tcl error code TCL READ VARNAME
ERROR: can't read "_line_unit_advertised_version": no such variable
    while executing
"if {$_line_unit_advertised_version == "default"} {
            set _line_unit_advertised_version $_line_unit_version
        }"
...

Fix this by using the correct variable name in two places in Dwarf::lines:
use _line_unit_advertised_version instead of _line_advertised_unit_version.

Tested on x86_64-linux.