[gdb/testsuite] Remove unnecessary perror in some test-cases
On openSUSE Tumbleweed I noticed:
...
UNTESTED: gdb.dwarf2/fission-absolute-dwo.exp: fission-absolute-dwo.exp
ERROR: failed to compile fission-absolute-dwo
...

The ERROR is unnecessary, given that an UNTESTED is already emitted.

Furthermore, it could be argued that it is incorrect because it's not a
testsuite error to not be able to compile something, and UNTESTED or
UNSUPPORTED is more appropriate.

Remove the perror call, likewise in fission-relative-dwo.exp.

Tested on x86_64-linux.