loongarch gcc-4.5 build fixes
Yet another case of missing fields in struct initialisation, which
I've replaced with a memset, and some complaints about identifiers
shadowing global declarations.  Fixing the shadowing in
loongarch-parse.y is easy.  This one isn't so easy:
gas/expr.c: In function 'expr':
gas/expr.c:1891:12: error: declaration of 'is_unsigned' shadows a global declaration
include/opcode/loongarch.h:224:14: error: shadowed declaration is here

opcode/loongarch.h declares lots of stuff that shouldn't be made
available to generic gas code, so I've removed that header from
tc-loongarch.h and moved the parts of TC_FORCE_RELOCATION_SUB_LOCAL
and TC_FORCE_RELOCATION_SUB_LOCAL that need LARCH_opts to functions
in tc-loongarch.c

	* config/loongarch-parse.y (loongarch_parse_expr): Rename
        param to avoid shadowing.
	* config/tc-loongarch.c (loongarch_assemble_INSNs): Use memset
	rather than struct initialisation.
	(loongarch_force_relocation_sub_local): New function.
	(loongarch_force_relocation_sub_same): Likewise.
	* config/tc-loongarch.h: Don't include opcode/loongarch.h.
	(loongarch_force_relocation_sub_local): Declare, and..
	(TC_FORCE_RELOCATION_SUB_LOCAL): ..use here.
	(loongarch_force_relocation_sub_same): Declare, and..
	(TC_FORCE_RELOCATION_SUB_SAME): ..use here.