gdb: fix compile break when HAVE_LIBEXPAT is not defined
Fixes:

      CXX    xml-tdesc.o
    /home/smarchi/src/binutils-gdb/gdb/xml-tdesc.c: In function const target_desc* file_read_description_xml(const char*):
    /home/smarchi/src/binutils-gdb/gdb/xml-tdesc.c:681:60: error: too few arguments to function target_desc* tdesc_parse_xml(const char*, xml_fetch_another, void*)
      681 |   return tdesc_parse_xml (tdesc_str->data (), fetch_another);
          |                                                            ^
    /home/smarchi/src/binutils-gdb/gdb/xml-tdesc.c:44:1: note: declared here
       44 | tdesc_parse_xml (const char *document, xml_fetch_another fetcher,
          | ^~~~~~~~~~~~~~~

Commit 51219385da07 ("gdb: change xml_fetch_another a function_view")
removed the `baton` parameter of `tdesc_parse_xml`, but didn't update
the version of the function used when GDB is built with no libexpat
support.  Remove the parameter in that definition too.

gdb/ChangeLog:

	* xml-tdesc.c [!defined(HAVE_LIBEXPAT)] (tdesc_parse_xml):
	Remove baton parameter.

Change-Id: I4ad29fbb7c3323f30ce5204c2976eaea16151a2e