Fix AIX CI build break.
In AIX a recent commit caused a build break with the error as shown below.
In file included from python/py-color.h:23,
                 from python/python.c:39:
python/python-internal.h:86:10: fatal error: Python.h: No such file or directory
   86 | #include <Python.h>

In AIX, we run builds with and without python for our internal CI's.

A feature development made by the recent commit https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=a4d1129283a3481dc2391fc32b64e62bdb7e21a7
missed to guard Python.h in HAVE_PYTHON macro.

This commit is a fix for the same.

Approved-By: Tom Tromey <tom@tromey.com>