[gdb/testsuite] Fix tcl error in gdb.mi/list-thread-groups-available.exp
When running gdb.mi/list-thread-groups-available.exp, we get:
...
Running gdb.mi/list-thread-groups-available.exp ...
ERROR: tcl error sourcing gdb.mi/list-thread-groups-available.exp.
ERROR: Too many arguments to gdb_test_multiple
...

The problem is that the gdb_test_multiple call has as last argument a
$mi_gdb_prompt, which is no longer supported syntax since 1456fa6dfc
"[gdb/testsuite] Add -lbl option in gdb_test_multiple".

Fix this by using the new -prompt syntax.

Tested on x86_64-linux.

gdb/testsuite/ChangeLog:

2020-03-03  Tom de Vries  <tdevries@suse.de>

	* gdb.mi/list-thread-groups-available.exp: Use -prompt syntax for
	gdb_test_multiple call.