Fix file-not-found error with clang in gdb.arch/i386-{avx,sse}.c
Clang fails to compile two testcases with the following error:
  fatal error: 'nat/x86-cpuid.h' file not found

This prevents the following testcases from executing:
  gdb.arch/i386-avx.exp
  gdb.arch/i386-sse.exp

Both testcases set additional_flags when building with GCC.
This commit causes the additional_flags to also be used when
building with clang.  Note that, while fixing the build, this
commit reveals several new failures when using clang to build
the testsuite.

gdb/testsuite/ChangeLog:

	* gdb.arch/i386-avx.exp (additional_flags): Also set when
	building with clang.
	* gdb.arch/i386-sse.exp (additional_flags): Likewise.