testsuite: Restore gdb_is_target_remote_prompt
In patch

  Add test for load command
  a7ccf1e1b5e103e424ff20ce4b4d324c2e9d3ffa

I removed gdb_is_target_remote_prompt, but did not realize it was used
in mi_is_target_remote.  This makes the gdb.mi/mi-nonstop.exp crash, for
example:

  ERROR: (DejaGnu) proc "gdb_is_target_remote_prompt {[(]gdb[)]
  }" does not exist.
  The error code is TCL LOOKUP COMMAND gdb_is_target_remote_prompt
  The info on the error is:
  invalid command name "gdb_is_target_remote_prompt"
      while executing
  "::tcl_unknown gdb_is_target_remote_prompt {[(]gdb[)]
  }"
      ("uplevel" body line 1)
      invoked from within
  "uplevel 1 ::tcl_unknown $args"

This patch restores it.

gdb/testsuite/ChangeLog:

	* lib/gdb.exp (gdb_is_target_1): Add prompt_regexp parameter and
	use it.
	(gdb_is_target_remote_prompt): New proc.
	(gdb_is_target_remote): Use gdb_is_target_remote_prompt.
	(gdb_is_target_native): Pass prompt parameter to
	gdb_is_target_1.