[gdb/testsuite] Fix gdb.base/return.exp on arm-linux
After doing pre-commit testing of some patch on arm-linux, the Linaro CI
reported:
...
FAIL: 1 regressions: 1 improvements

regressions.sum:
		=== gdb tests ===

Running gdb:gdb.base/return.exp ...
ERROR: no fileid for ccd235fdc9bf

improvements.sum:
		=== gdb tests ===

Running gdb:gdb.base/return.exp ...
ERROR: no fileid for 017e9b314c5a
...

The problem is the call to allow_float_test.  It calls gdb_exit (for arm-linux
only), and consequently kills the gdb instance setup by prepare_for_testing:
...
if { [prepare_for_testing "failed to prepare" "return"] } {
     return -1
}

set allow_float_test [allow_float_test]
...

Fix this by moving the call to allow_float_test to before prepare_for_testing.

Tested on arm-linux and x86_64-linux.