gas: Update testsuite/gas/symver/symver15.l
Update testsuite/gas/symver/symver15.l to expect:

Error: multiple versions [`foo@version2'|`foo@version1'] for symbol `foo'

	* testsuite/gas/symver/symver15.l: Expect '|'.

Signed-off-by: H.J. Lu <hjl.tools@gmail.com>