Hurd: Adjust to "Per-inferior/Inferior-qualified thread IDs" changes
    [...]/gdb/gnu-nat.c: In function 'set_sig_thread_cmd':
    [...]/gdb/gnu-nat.c:2973:7: warning: implicit declaration of function 'thread_id_to_pid' [-Wimplicit-function-declaration]
           ptid_t ptid = thread_id_to_pid (atoi (args));
           ^
    [...]/gdb/gnu-nat.c:2973:7: error: invalid initializer

That's commit 564ad09e056a07776531695bf449980d95b056a8, which renamed
`thread_id_to_pid` to `global_thread_id_to_ptid`.

	gdb/
	* gnu-nat.c (set_sig_thread_cmd): Call global_thread_id_to_ptid
	instead of thread_id_to_pid.