gdb/mips: fix lwp_info ptr -> ref
Fix this:

  CXX    mips-linux-nat.o
/home/smarchi/src/binutils-gdb/gdb/mips-linux-nat.c: In function ‘int write_watchpoint_regs()’:
/home/smarchi/src/binutils-gdb/gdb/mips-linux-nat.c:640:39: error: cannot convert ‘lwp_info’ to ‘const lwp_info*’ in initialization
  640 |   for (const lwp_info *lp : all_lwps ())
      |                                       ^

... which is a fallout of 7ad32d93def4 ("gdb: make lwp_info_iterator
yield references").

Change-Id: I3cfb9eb597bea6c6921219bbf28937784fd8ac55