[gdb/testsuite] Fix tcl ERROR in gdb_load_no_complaints
In commit b6f3a091af9 "[gdb/symtab] Fix element type modification in
read_array_type" I factored out new proc with_complaints out of proc
gdb_load_no_complaints, but when fixing a rebase conflict pre-commit I made a
mistake in gdb_load_no_complaints that is now causing:
...
ERROR: tcl error sourcing dw2-ranges-psym.exp.
ERROR: can't read "save": no such variable
    while executing
"gdb_test_no_output "set complaints $save" """
    (procedure "gdb_load_no_complaints" line 14)
    invoked from within
"gdb_load_no_complaints $binfile"
...

Fix this by removing the offending line.

Tested on x86_64-linux.

gdb/testsuite/ChangeLog:

2021-02-10  Tom de Vries  <tdevries@suse.de>

	* lib/gdb.exp (gdb_load_no_complaints): Remove unnecessary
	"Restore saved setting of complaints".