x86-64: Skip SCFI tests for x32 targets
Since SCFI isn't supported on x32:

Fatal error: SCFI is not supported for this ABI

skip SCFI tests for x32 targets.

	PR gas/31245
	* testsuite/gas/scfi/x86_64/scfi-x86-64.exp: Skip for x32
	targets.