[gdb/testsuite] Fix gdb.base/exec-invalid-sysroot.exp
Since commit ea11eaf6701 ("gdb/testsuite: also compile foll-exec.exp as C++"),
we run into:
...
Running gdb.base/exec-invalid-sysroot.exp ...
gdb compile failed, foll-exec.c: In function 'main':
foll-exec.c:35:52: error: 'EXECD_PROG' undeclared (first use in this function)
   printf ("foll-exec is about to execlp(%s)...\n", EXECD_PROG);
                                                    ^~~~~~~~~~
foll-exec.c:35:52: note: each undeclared identifier is reported only once \
  for each function it appears in
...

Fix this by default-defining EXECD_PROG to "execd-prog".

Tested on x86_64-linux.