gdb/solib-target: move make_target_solib_ops out of HAVE_LIBEXPAT
When building without expat, we get a missing make_target_solib_ops
error:

    /usr/bin/ld: arch-utils.o: in function `gdbarch::gdbarch()':
    /home/simark/src/binutils-gdb/gdb/gdbarch-gen.c:30:(.text+0x15be): undefined reference to `make_target_solib_ops()'

Fix it by moving make_target_solib_ops out of HAVE_LIBEXPAT.

Bug: https://sourceware.org/bugzilla/show_bug.cgi?id=33118
Change-Id: I76fe4698c6b71bd76096e6cdcbacf8de42a3eb43
Tested-by: Thiago Jung Bauermann <thiago.bauermann@linaro.org>