gdb/testsuite: use unresolved in mi_run_cmd_full
Running:

    make check TESTS="gdb.mi/mi-nonstop-exit.exp" RUNTESTFLAGS="--target_board=native-extended-gdbserver"

We get:

    Running /home/simark/src/binutils-gdb/gdb/testsuite/gdb.mi/mi-nonstop-exit.exp ...
    ERROR: Unable to start target

                    === gdb Summary ===

    # of expected passes            2

The root cause of the problem is the typical "we try to enable non-stop
after having connected to gdbserver".  This is because with the
native-extended-gdbserver board, GDB connects to GDBserver as soon as
it's started.  It's too late then to do "set non-stop 1" or "-gdb-set
non-stop 1".  This is fixed by the following patch.

More worrying is that the error is not reported (except for the
printout).  From the testsuite point of view, everything went fine.
runtest exits with status 0.

This is because mi_run_cmd_full uses perror.  perror just prints that
ERROR and makes it so the next test becomes UNRESOLVED.  However,
there's no next test, because we just return early, seeing that we
couldn't run.

Change mi_run_cmd_full to call unresolved directly instead.  This
ensures that the failure is recorded.

This is the results diff when running the gdb.mi/*.exp tests:

     # of unexpected failures       34
     # of expected failures         8
     # of known failures            13
    -# of unresolved testcases      4
    +# of unresolved testcases      10
     # of unsupported tests         1
     # of duplicate test names      34

gdb/testsuite/ChangeLog:

	* lib/mi-support.exp (mi_run_cmd_full): Use unresovled instead
	of perror.

Change-Id: Ib0f214c0127fbe73f2033c6c29d678e025690220