GDB/testsuite: Fix a typo in $actual_line
Fix a commit baaf601e8817 ("Record nested types") issue:

ERROR: tcl error sourcing .../gdb/testsuite/gdb.cp/nested-types.exp.
ERROR: can't read "actual_linejj": no such variable
    while executing
"append txt " definition: $actual_linejj""
    (procedure "cp_test_ptype_class" line 324)
    invoked from within
"cp_test_ptype_class $name "ptype $name (limit = $limit)" $key  $name $children"    (procedure "test_nested_limit" line 28)
    invoked from within
"test_nested_limit -1 false"
    (file ".../gdb/testsuite/gdb.cp/nested-types.exp" line 310)
    invoked from within
"source .../gdb/testsuite/gdb.cp/nested-types.exp"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 source .../gdb/testsuite/gdb.cp/nested-types.exp"
    invoked from within
"catch "uplevel #0 source $test_file_name""
testcase .../gdb/testsuite/gdb.cp/nested-types.exp completed in 9 seconds

caused by $actual_line having been accidentally referred to as
$actual_linejj in one place.

	gdb/testsuite/
	* lib/cp-support.exp (cp_test_ptype_class): Fix a typo in the
	name of a variable: $actual_linejj -> $actual_line.