gdbserver: make aarch64_write_goto_address static
This function is only used in this file, so make it static.  It fixes
this error, when building with -Wmissing-declarations:

  CXX    linux-aarch64-low.o
/home/simark/src/binutils-gdb/gdb/gdbserver/linux-aarch64-low.c:2642:1: error: no previous declaration for 'void aarch64_write_goto_address(CORE_ADDR, CORE_ADDR, int)' [-Werror=missing-declarations]
 aarch64_write_goto_address (CORE_ADDR from, CORE_ADDR to, int size)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~

gdb/gdbserver/ChangeLog:

	* linux-aarch64-low.c (aarch64_write_goto_address): Make static.