gdb: TYPE_VECTOR -> type::is_vector in amd64-windows-tdep.c
I get this build failure:

      CXX    amd64-windows-tdep.o
    cc1plus: warning: command-line option '-Wmissing-prototypes' is valid for C/ObjC but not for C++
    /home/smarchi/src/binutils-gdb/gdb/amd64-windows-tdep.c: In function 'return_value_convention amd64_windows_return_value(gdbarch*, value*, type*, regcache*, gdb_byte*, const gdb_byte*)':
    /home/smarchi/src/binutils-gdb/gdb/amd64-windows-tdep.c:374:6: error: 'TYPE_VECTOR' was not declared in this scope
      374 |  if (TYPE_VECTOR (type) && len == 16)
          |      ^~~~~~~~~~~

TYPE_VECTOR was removed in favor of the type::is_vector method.

gdb/ChangeLog:

	* amd64-windows-tdep.c (amd64_windows_return_value): Use
	type::is_vector instead of TYPE_VECTOR.

Change-Id: I0ce26c3f7a33625761a8dba351c3158464f21b01